### ISSUE TITLE
fits headers in catalog files

### ISSUE THREAD

**Issue by sbailey** [ameisner/ci_reduce#15]
Please propagate the same FITS headers in the reduced files into the catalog files as well, so that the catalog files can be used standalone without having to look up header keywords from the separate and much larger reduced files.  Thanks.

**Comment by ameisner** [comment]
I'll work on putting this in place...

**Comment by ameisner** [comment]
I think I've done this in https://github.com/ameisner/gfa_reduce/commit/dfddd5b89b2bfdc8fda0c138f7c6779c657a15a3

An example file with the new extensions tacked on is at:

http://faun.rc.fas.harvard.edu/ameisner/gfa-00020012_catalog.fits
