### ISSUE TITLE
Allow intermediate processing from multiple nights

### ISSUE THREAD

**Issue by weaverba137** [ameisner/ci_reduce#19]
To account for the possibility of NERSC downtime, intermediate GFA processing should always check for any available unprocessed exposures, not just exposures from the previous night.

**Comment by weaverba137** [comment]
One approach would be to read nights and exposures from the most recent summary file, then identify any more recent nights and exposures that are not in that summary file.

**Comment by dli-astro** [comment]
I am trying to get all pre-summer-2023 GFA guide images on NERSC reduced. Once that is done, another approach would be to compare sub-folders in the directories for the raw and reduced data. Anyway, I will work on this asap.

**Comment by weaverba137** [comment]
This was closed by #18
