### ISSUE TITLE
Do we still want to be labeling summary files 'SV3'?

### ISSUE THREAD

**Issue by weaverba137** [ameisner/ci_reduce#22]
Despite starting the main survey a while ago, GFA summary files are still labeled with `SV3`. This is an easily changeable option.

Is there any desire to change? Is there any benefit to renaming older summary files that are from the main survey? For example, one (and only one) summary file will be released in DR1, but it's still called `SV3`.

@schlafly @sbailey

**Comment by schlafly** [comment]
I'm totally happy if we want to drop the SV3 descriptor and just go with the date.  In my recollection the tsnr afterburner is the only piece of code that looks for this, so it probably isn't too bad to clean up the things that reference it; if you're convinced you know where those are, great.

But I'm also happy to do nothing.

**Comment by sbailey** [comment]
I'm also happy with cleaning this up on the gfa_reduce side, and then fixing anything downstream like tsnr_afterburner that is impacted.

**Comment by weaverba137** [comment]
@sbailey and I agreed that we can rename `SV3` to `main`, but we will do that after I get back from vacation, effectively 2nd half of March.

**Comment by weaverba137** [comment]
Closed by #20.
